apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: testjob
spec:
  parallelism: 2
  completions: 8
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: busybox
        name: testjob
        command: ["sh"]
        args: ["-c", "echo 'helll world'"]
      restartPolicy: OnFailure
status: {}
